### ISSUE TITLE
Where can i change the header / background color?

### ISSUE THREAD

**Issue by NH3CL** [cabot/black#2]
Hi Team,

For first of all, thank you for this theme.

Could you please tell me, where can I change the background color of the header?
Thanks in advance!

**Comment by cabot** [comment]
Hello,

Add your custom CSS rule in `_custom.scss` then recompile `stylesheet.css` and purge the cache.
i.e:
```css
.headerbar {
    background-color: blue;
}
```
